version: '3.8'

services:
  MAILMIND2.o:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mailmind-app
    ports:
      - "8501:8501"
    volumes:
      - ./credentials:/app/credentials
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - mailmind-network

  redis:
    image: redis:7-alpine
    container_name: mailmind-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - mailmind-network
    command: redis-server --appendonly yes

  nginx:
    image: nginx:alpine
    container_name: mailmind-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - mailmind-app
    restart: unless-stopped
    networks:
      - mailmind-network

volumes:
  redis_data:
    driver: local

networks:
  mailmind-network:
    driver: bridge
